### ISSUE TITLE
Add Python 3.14 support once homebrew certifi is fixed

### ISSUE THREAD

**Issue by MaxGhenis** [GrantKit/grantkit#10]
## Summary

Python 3.14 is now stable, but grantkit doesn't work with homebrew's Python 3.14 due to a broken certifi installation that causes:

```
AttributeError: module 'certifi' has no attribute 'where'
```

This happens when httpx (used by supabase) tries to create an SSL context.

## Root Cause

Homebrew's Python 3.14 has a broken/incomplete certifi package (just an empty `__pycache__` directory instead of the full package).

## Related Issues

- https://github.com/certifi/python-certifi/issues/349

## Workaround

Install grantkit with pipx using Python 3.13:
```bash
pipx install grantkit --python python3.13
```

## Action Items

- [ ] Monitor the certifi issue for a fix
- [ ] Once homebrew's certifi is fixed, add Python 3.14 to pyproject.toml classifiers
- [ ] Test on Python 3.14 before releasing
